databaseChangeLog:
  - changeSet:
      id: 1
      author: dan
      changes:
        - createTable:
            tableName: destination
            columns:
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    primaryKey: true
                    nullable: false
                    unique: true